---

- name: "configuration play." 
  hosts: web
  user: ubuntu

  vars:
  
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml
      
  gather_facts: false  
    
  roles:
    - deploy
    - configure-prometheus-node-exporter
