---

- name: "configuration play." 
  hosts: web
  user: ubuntu
  gather_facts: true
  vars:
  
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml
    - ENVIRONMENT: "{{ lookup('env','ENVIRONMENT') }}"
    - CIRCLE_WORKFLOW_ID: "{{ lookup('env','CIRCLE_WORKFLOW_ID') }}"
    - TYPEORM_CONNECTION: "{{ lookup('env','TYPEORM_CONNECTION') }}"
    - TYPEORM_ENTITIES: ./src/modules/domain/**/*.entity.ts
    - TYPEORM_HOST: "{{ lookup('env','TYPEORM_HOST') }}"
    - TYPEORM_PORT: 5432
    - TYPEORM_USERNAME: "{{ lookup('env','TYPEORM_USERNAME') }}"
    - TYPEORM_PASSWORD: "{{ lookup('env','TYPEORM_PASSWORD') }}"
    - TYPEORM_DATABASE: "{{ lookup('env','TYPEORM_DATABASE') }}"
    - TYPEORM_MIGRATIONS: .src/migrations/*.ts
    - TYPEORM_MIGRATIONS_DIR: ./src/migrations
    
  roles:
    - deploy
    - configure-prometheus-node-exporter
