---
- name: "Creates directory"
  file:
    path: /home/ubuntu/backend
    state: directory
    
- ansible_ssh_common_args: "-o StrictHostKeyChecking=no"    
    
- name: "Move backend files to remote server."
  become: true
  copy:
    src: /root/project/backend
    dest: /home/ubuntu

- name: "Install dependencies"
  shell: |
    cd /home/ubuntu/backend   
    ls -la 
    npm install
    
- name: "build package"
  become: true
  shell: |
    cd /home/ubuntu/backend
    npm run build
- name: "run server"
  become: true
  shell: |
    cd /home/ubuntu/backend
    pm2 start npm -- run "start:dev"
    pm2 ls

