- name: Copy backend files
  become: true
  copy:
    src: /home/backend.tar.gz
    dest: /home/ubuntu/backend.tar.gz
    
- name: "copy backend binaries"
  become: yes
  synchronize:
    src: ../../backend/dist
    dest: /home/ubuntu/backend
    recursive: true

- name: "copy node_modules"
  become: yes
  synchronize:
    src: ../../backend/node_modules
    dest: /home/ubuntu/backend
    recursive: true
    
- name: "copy packages"
  become: yes
  synchronize:
    src: ../../backend
    dest: /home/ubuntu/backend
    recursive: false

- name: Prepare Env
  shell: |
    sudo npm i
    npm i pm2 -g
    sudo npm i npm@latest -g
    sudo npm i webpack-dev-server -g
  args:
    chdir: /home/ubuntu/backend/dist
    
- name: Start PM2
  become: true
  command: pm2 start main.js --update-env
  args:
    chdir: /home/ubuntu/backend/dist
  environment:
    ENVIRONMENT: production
    TYPEORM_CONNECTION: "{{ lookup('env', 'TYPEORM_CONNECTION') }}"
    TYPEORM_MIGRATIONS_DIR: "./migrations"
    TYPEORM_MIGRATIONS: "./migrations/*.js"
    TYPEORM_ENTITIES: "./modules/domain/*/entities/*.entity.js"
    TYPEORM_HOST: "{{ lookup('env', 'TYPEORM_HOST') }}"
    TYPEORM_PORT: "{{ lookup('env', 'TYPEORM_PORT') }}"
    TYPEORM_USERNAME: "{{ lookup('env', 'TYPEORM_USERNAME') }}"
    TYPEORM_PASSWORD: "{{ lookup('env', 'TYPEORM_PASSWORD') }}"
    TYPEORM_DATABASE: "{{ lookup('env', 'TYPEORM_DATABASE') }}"
