- name: Copy backend dist files web server
  copy:
    src: /root/project/artifact.tar.gz
    dest: /home/ubuntu/artifact.tar.gz

- name: Uncompress Backend
  shell: |
    cd /home/ubuntu
    tar xvzf artifact.tar.gz -C .
    ls -la

- name: "Copy package.json to server"
  become: true
  copy:
    src: /root/project/backend/package.json
    dest: /home/ubuntu/
    owner: ubuntu

- name: "Install backend dependencies using NPM"
  command: npm install --production
  args:
    chdir: /home/ubuntu

- name: "Start backend with pm2"
  shell: |
    export ENVIRONMENT=production
    export NODE_ENV=production
    export TYPEORM_HOST="{{ lookup('env', 'TYPEORM_HOST') }}"
    export TYPEORM_ENTITIES="{{ lookup('env', 'TYPEORM_ENTITIES') }}"
    export TYPEORM_USERNAME="{{ lookup('env', 'TYPEORM_USERNAME') }}"
    export TYPEORM_PASSWORD="{{ lookup('env', 'TYPEORM_PASSWORD') }}"
    export TYPEORM_DATABASE="{{ lookup('env', 'TYPEORM_DATABASE') }}"
    cd src
    pm2 start main.ts --name udapeople-backend
  args:
    chdir: /home/ubuntu

- name: "Set pm2 start as service"
  become: yes
  shell: |
    env PATH=$PATH:/usr/local/bin pm2 startup -u ubuntu
